### ISSUE TITLE
Version file causes a fatal error in foreach()

### ISSUE THREAD

**Issue by hdodov** [distantnative/retour-for-kirby#154]
I installed Retour and got the following error:

![image](https://user-images.githubusercontent.com/5570098/75054458-c2bda180-54db-11ea-9cc0-de0b6256bfd0.png)

On the next request, the `.retour` file was created and I was no longer getting the error.

---

I think it's redundant to have just the version of the plugin in a separate file that could even cause errors. I can see that the reason for that is to know if the contained data has the correct schema according to the plugin version, but is that _really_ needed? How often would you change that schema? How severe consequences will that have? I think it's a bit over-engineered.

At the very least, you could store that version in the `redirects.yml` and have:

```yml
schema: "2.3.1"
entries:
  - 
    status: "200"
    from: foo
    to: /bar
    hits: "0"
    last: null
  - 
    status: "200"
    from: bar
    to: baz
    hits: "0"
    last: null
```

I find it kind of annoying that I have to track a file in Git that contains just some version number. Why is that file there? What is it used for? It's polluting.

---

All of that aside - the plugin rocks! 🤘
