### ISSUE TITLE
Redirects page cannot be loaded at panel after update to 3.0.0

### ISSUE THREAD

**Issue by ankeknicker** [distantnative/retour-for-kirby#223]
Hi,

we are getting the problem, that the Redirects page at panel fails loading after updating to version 3.0.0. The redirects are already working, but I get the following messages at the kirby panel (only on production or review environment, at localhost it works):

![image](https://user-images.githubusercontent.com/9609156/107515062-ccd42680-6baa-11eb-98d9-d8e38b2c3ebc.png)

![Bildschirmfoto 2021-02-10 um 11 38 05](https://user-images.githubusercontent.com/9609156/107515147-ef663f80-6baa-11eb-9c81-33ef991e041e.png)

After turning debug mode to on, the browser console prints out the following:

![Bildschirmfoto 2021-02-10 um 12 29 31](https://user-images.githubusercontent.com/9609156/107515326-289eaf80-6bab-11eb-9030-cde30227ae82.png)

**Comment by distantnative** [comment]
Hi @ankeknicker,

I just released a new version of the plugin that also improves the upgrade mechanism. Maybe this fixes your issue already.
Otherwise it would be great if you could post (or send me privately, nico@getkirby.com) a copy of your `site/config/redirects.yml` for debugging.

**Comment by ankeknicker** [comment]
Hi @distantnative 
unfortunally the new release didn't fixed the problem.

This is my redirects.yml:

```
routes:
  - 
    from: leistungen/(:all)
    to: /themen/$1
    status: 308
    priority: null
    comment: null
  - 
    from: team
    to: /ueber/team
    status: 301
    priority: false
    comment: null
  - 
    from: jobs
    to: /karriere
    status: 301
    priority: false
    comment: null
  - 
    from: jobs/(:all)
    to: /karriere/$1
    status: 301
    priority: false
    comment: null
  - 
    from: en
    to: /
    status: 307
    priority: false
    comment: null
  - 
    from: en/(:all)
    to: /$1
    status: 307
    priority: false
    comment: null
schema: 3.0.0
```
