### ISSUE TITLE
4.0.0-beta.1: Redirect with placeholder not working

### ISSUE THREAD

**Issue by yatil** [distantnative/retour-for-kirby#264]
## Describe the bug

Redirects with placeholders are not working (for me). Redirects without placeholders seem to work fine.

## Steps to reproduce

  1. Go to https://knowbility.org/programs/accessu/2021
  1. You are getting a 404 error.

## Expected behavior

Being redirected to https://knowbility.org/programs/accessu-2021

## Additional context

The route is set up as follows:

```yaml
redirects:
  -
    from: programs/accessu/(:num)
    to: /programs/accessu-$1
    status: 301
    priority: false
    comment: null
```

![screenshot of route with above data](https://cln.sh/EVuY0AGWA3JPEsPYfZJv/download)

## Specifications

  - Retour version: 4.0.0-beta.1
  - Retour config options: default
  - Kirby version: 3.6.1.1
  - Browser: any
