### ISSUE TITLE
4.0: UI redirects to 404 page

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#282]
We have paths like `projekte-mit-filter/tag/Kultur%252520%252526%252520Denkmalschutz.html` coming from a legacy CMS. Clicking these entries in the table of routes results in a redirect to `/panel/dialogs/retour/redirects/projekte-mit-filter%2Ftag%2FKultur%252520%252526%252520Denkmalschutz.html/edit?column=from` which returns a 404 page.

Other routes work just fine. 
This is the corresponding definition:

```yaml
  - 
    from: 'projekte-mit-filter/tag/Kultur%2520%2526%2520Denkmalschutz.html'
    to: projekte/kategorie:kultur-denkmalschutz
    status: 301
    priority: false
    comment: null
```
