### ISSUE TITLE
4.0: Empty line may currupt retour.yml

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#283]
We've got a list of old URLs from a legacy CMS that we'd like to add to Retour. Because of the number of routes, creating `retour.yml` in the editor was easier than using the interface. The editor formats YAML using Prettier resulting in the following example file:

```yaml
redirects:
  - from: wechselblick-festival-2018-ein-erlebnis-der-vielfalt-vor-unserer-haustür.html
    to: replace
    status: 301
    priority: false
    comment: ?file=files/projekte/2015/Sommerkino%202015/Braunschweiger%20Zeitung%2014.07.2015.pdf
```

Everything load perfectly fine in the Retour interface. But after adding a new entry via the panel, the formatting changes on save:

```yaml
redirects:
  - 
    from: loesch/mich
    to: test
    status: null
    priority: false
    comment: null
  - 
    from: >
      wechselblick-festival-2018-ein-erlebnis-der-vielfalt-vor-unserer-haustür.html
    to: replace
    status: 301
    priority: false
    comment: '?file=files/projekte/2015/Sommerkino%202015/Braunschweiger%20Zeitung%2014.07.2015.pdf'
```

When I now adjust any redirect in my editor, Prettier formats the content again (note the empty line that's added for whatever reason):

```yaml
redirects:
  - from: loesch/mich
    to: test
    status: null
    priority: false
    comment: null
  - from: >
      wechselblick-festival-2018-ein-erlebnis-der-vielfalt-vor-unserer-haustuer.html

    to: replace
    status: 301
    priority: false
    comment: '?file=files/projekte/2015/Sommerkino%202015/Braunschweiger%20Zeitung%2014.07.2015.pdf'
```

Saving again from the panel and now all the data is corrupted (check the gibberish in the second definition):

```yaml
redirects:
  - 
    from: loeschmich
    to: test
    status: null
    priority: false
    comment: null
  - 
    from: |
      wechselblick-festival-2018-ein-erlebnis-der-vielfalt-vor-unserer-haustuer.html
      : replace atus: 301 iority: false mment: '?file=files/projekte/2015/Sommerkino%202015/Braunschweiger%20Zeitung%2014.07.2015.pdf'
    to: null
    status: null
    priority: false
    comment: null
```
