### ISSUE TITLE
Permissions: read-only access for editors

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#372]
Currently the redirections editing pages and redirections log are accessible to all Panel users by default, and access can be fully blocked for a role with:

```yaml
permissions:
  access:
    retour: false
```

As documented here: https://distantnative.com/retour-for-kirby/options#permissions

Ideally, I'd like to restrict *managing redirections* to admins, but give read-only access to the configured redirections and the redirection logs to an `editor` role.

My use case is that most configured redirections are a bit technical and handle old URL patterns from a previous version of a website (before it was redesigned and rewritten in Kirby), so I don't want clients to modify them. But giving them read-only access to the redirection logs, and especially the failures, would be useful for their content and SEO work.

I tried something like this on the off chance that it was supported but not documented (doesn't seem to be):

```yaml
# site/blueprints/users/editor.yml
permissions:
  access:
    retour: true
  retour:
    read: true
    create: false
    update: false
    delete: false
```

Do you think that's something that would be interesting?
