### ISSUE TITLE
Make routing optional for non-admin users

### ISSUE THREAD

**Issue by jschopplich** [distantnative/retour-for-kirby#54]
Non-admin users can't edit redirects, but can click on the add button. If texting anything at all into on of the input fields the plugin immediately redirects to the panel's index URL. That's... misleading.

Maybe don't show the Retour plugin page not at all or make it optional for users?

```yml
title: Editor

permissions:
  access:
    retour: false

```

**Comment by distantnative** [comment]
This is a big one. I completely avoided the permissions topic so far. I don't think plugins can hook into the blueprint settings option as you suggested, but I will have a look. I might go for the easy way first to only make it available for the admin role. Then again, we need to check what Kirby panel view plugins can actually do about that. I have added the bug label nevertheless, cause the described way of being able to do one thing but not the other surely is not how it should be at all.

**Comment by jschopplich** [comment]
Yeah, I guessed so. 😄 I think it would be a safe workaround to first make it available for admins and add other options later. Aren't blueprints just readable fields since K3? Therefore maybe it ain't that complicated. But I don't know.

**Comment by distantnative** [comment]
Could you share with me the roles/user blueprint of the role you are talking about? I just checked it with a simple editor role and that one can do everything without problems:

```
title: Editor

permissions:
  access:
    panel: true
```

So it must be additional permissions. I would assume that your role is not allowed to update `site`. Is that correct?

**Comment by jschopplich** [comment]
Yes, that is correct.

```
permissions:
  access:
    settings: false
  users: false
  site:
    update: false
  user:
    create: false
    deleteAvatar: false
    changeRole: false
    delete: false
```

**Comment by distantnative** [comment]
Beta 4 will have simple permissions handling ✅

### Access (can't see plugin screen)

```yaml
title: Editor

permissions:
  access:
    retour: false
```

### Update (can see plugin screen but not modify any data)

```yaml
title: Editor

permissions:
  site:
    update: false
```
